config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :controllers =>{ :registrations => "user_registrations" }}

  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]



  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'

  get 'payments/thanks_message'
  post 'payments/create'


  post 'static_pages/thank_you'

  root 'static_pages#landing_page'


  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments
  validates :name, presence: true

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end

  def average_rating
    comments.average(:rating).to_f
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # before_filter :authenticate_user!
  before_action :authenticate_user!, :except => [:show, :index]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index

    if params[:q]
      search_term = params[:q]
      @products = Product.where("name Like ?", "%#{search_term}%")

    else
      @products = Product.all

    end
    # byebug
  end
  # this is how we write a filted list of products that match or get as close to their search name,the other case is that if the user navigates to the index page without entering a search term, we want them to see all products instead.For our search condition, we will use the Active Record where method, to find products where their name matches the search_term variable. Most users may enter just part of the name if they can’t remember the whole thing. For this, SQL has a useful matching operator called LIKE,but In order to be able to search for words while ignoring whether some letters are upper or lower case, you need to use "ilike" and it allows you to include a “wildcard” character (%) to indicate that the matching term may be part of a longer string.So we need to put percentage characters around our search_term string.

  # GET /products/1
  # GET /products/1.json
  def show
    @comment = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
  end

  # GET /products/new
  def new

    @products = Product.new

  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create

    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to 'product_url', notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url,  :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-comments">
   <h3><strong>Reviews:</strong></h3>
    <% @comment.each do |comment| %>
        <div class="row">
            <hr>
            <p>
            <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
            <% if signed_in? && (current_user.admin? || current_user.id == comment.user_id) %>
              <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe,product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </p>
            <p><%= comment.body %></p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
        </div>
    <% end %>

    <%= will_paginate @comment %>

</div>

</div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <!-- <div class="field">
    <label for="product_name">Name</label><br>
    <input id="product_name" name="product[name]" type="text" />
  </div> --> <!-- This will generate both a label and a text field for the name attribute of the product -->

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>



  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/_new_comment.html.erb
  <div class="add-review">

     <% if signed_in? %>
       <h3><strong>Add a review:</strong></h3>
       <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
         <p>
           <%= f.label :body, "Comments" %><br>
           <%= f.text_area (:body) %>
         </p>
         <p>
          <%= f.label :rating, "Your rating:" %>
           <div class="rating"></div>
         </p>
         <br>
         <p>
           <%= f.submit "Submit", class:"btn btn-default" %>
         </p>
       <% end %>
     <% end %>
  </div>

app/views/products/_product.html.erb
 <% @products.each do |product| %>
     <div class="col-sm-2 col-md-4">
      <h3><%= product.name%></h3>


      <% if product.image_url.present? %>
        <%= image_tag(product.image_url , class: "img-thumbnail img-responsive") %>
      <% end %>


      <br>
      <strong>Description<%= product.description %></strong>
      <br/>
      <strong>Colour:<%= product.colour %></strong>
      <br/>

      <strong>Price: $ <%= product.price %></strong>
      <br/>

      <%= link_to 'Show', product ,class:"btn btn-default"%>
      <%= link_to 'Edit', edit_product_path(product), class:"btn btn-default" %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default"%>
      <% logger.debug "Product: #{product.name}"%>
      <br>
      <br>
     </div> <!-- /col -->
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product, class:"btn btn-default" %> |
<%= link_to 'Back', products_path, class:"btn btn-default" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>


<div class="container-fluid">
  <div class="row">

      <%= render partial: "product" %>


  </div> <!-- row -->
</div> <!-- container -->


<%= link_to 'Create New Product', new_product_path, class: "btn btn-default" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>



<div class="row" data-product-id="<%= @product.id %>">

  <div class="col-sm-12 col-md-6">
    <br/>
    <br/>
    <h3><%= @product.name %></h3>
    <br>
    <div>
      <% if @product.image_url.present? %>
        <%= image_tag(@product.image_url, width: "500", class: "img-zoom img-thumbnail", data_zoom_image: "@product.image_url") %>
      <% end %>
    </div>
    <br/>
    <%= link_to 'Edit', edit_product_path(@product),class:"btn btn-default" %> |
    <%= link_to 'Back', products_path, class:"btn btn-default" %>

  </div><!--/col-->

  <div class="col-sm-12 col-md-6">
    <div class="product-info">
    <br>
     <br>

     <h4>
       <strong>Description:</strong>
       <%= @product.description %>
     </h4>
     <h4>
       <strong>Color:</strong>
       <%= @product.colour %>
     </h4>
      <br>
     <h4>
       <strong>Price: $</strong>
       <%= @product.price %>
     </h4>

     <br>
     <br>
      <h4><strong>Average Rating: </strong></h4>

     <%= @product.average_rating do %>
      <div class="rated" id="average_rating" data-score="<%= @product.average_rating %>">
     </div>
     <% end %>
     <br>
     <br>
     <br>
     <%= form_tag "/payments/create" do %>
      <%= hidden_field_tag(:product_id, @product.id) %>
       <%= render partial: "shared/stripe_checkout_button" %>




   </div><!--/product-info-->
  </div> <!--col-->
 <% end %>

</div><!-- container -->
<br>
<!-- <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
<div class="col-md-6 col-xs-12"> -->




  <%= render 'comments' %>
  <%= render 'new_comment' %>
</div>