config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :controllers =>{ :registrations => "user_registrations" }}

  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]



  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'

  get 'payments/thanks_message'
  post 'payments/create'


  post 'static_pages/thank_you'

  root 'static_pages#landing_page'


  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My_app</title>



    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all'  %>

    <%= javascript_include_tag 'application' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>



  </head>

  <body>



  <nav class="navbar navbar-default">
   <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">The Antiquarian</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
         <%= link_to '/static_pages/index' do %>
            <%= content_tag :span, "(current)", :class => "sr-only" %>
          Home
          <% end %>
        </li>

        <li><%= link_to "About", static_pages_about_path,class: "navigation-link" %></li>
        <li><%= link_to "Contact", static_pages_contact_path,class: "navigation-link" %></li>
        <li class="dropdown">
        <a href="../products" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">What we offer<span class="caret"></span></a>

          <ul class="dropdown-menu">
            <li><%= link_to "Featured Products", '/static_pages/landing_page',class: "navigation-link" %></li>
            <li><%= link_to "Products", products_path %></li>


         </ul><!--/dropdown-menu-->
        </li>
      </ul> <!--/navbar-nav-->
      <ul class="nav pull-right">
        <li>
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, style: "color: #34495e") %>
        <% else %>
          <%= link_to('Login',new_user_session_path, style:"color: #34495e") %>
        <% end %>
        </li>
      </ul><!--/pull-right-->
      <%= form_tag("/products", class:"navbar-form navbar-left", role:"search", method: "get") do %>
       <!--  <%= label_tag() %> -->
        <%= text_field_tag(:q, nil, class:"form-control", placeholder:"Search for...") %>
        <%= submit_tag("Search", class:"btn btn-default") %>
      <% end %>


    </div>
   </div>
  </nav>

 <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
  <% elsif alert %>
    <p id="alert" class="alert alert-warning"><%= alert %></p>
  <% end %>


  <%= yield %>

    <footer class="temp-footer">
      &copy; 2016 Jovanka N.
    </footer>

  </body>
</html>